package com.qtatelier.goverment.basics.bloguser.mapper;


import com.qtatelier.dto.BlogUser;
import com.qtatelier.goverment.response.UserResponse;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface BlogUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    int insert(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    int insertSelective(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    BlogUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    int updateByPrimaryKeySelective(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    int updateByPrimaryKey(BlogUser record);


    UserResponse selectByUserName(BlogUser blogUser);
}