package com.qtatelier.goverment.basics.bloguser.model;

public class BlogUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_id
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.userName
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.password
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.sign
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.location
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.web_url
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.callself
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String callself;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.nick_name
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.image_name
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String imageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_email
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.token
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.salt
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_id
     *
     * @return the value of blog_user.user_id
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_id
     *
     * @param userId the value for blog_user.user_id
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.userName
     *
     * @return the value of blog_user.userName
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.userName
     *
     * @param username the value for blog_user.userName
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.password
     *
     * @return the value of blog_user.password
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.password
     *
     * @param password the value for blog_user.password
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.sign
     *
     * @return the value of blog_user.sign
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.sign
     *
     * @param sign the value for blog_user.sign
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.location
     *
     * @return the value of blog_user.location
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.location
     *
     * @param location the value for blog_user.location
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.web_url
     *
     * @return the value of blog_user.web_url
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.web_url
     *
     * @param webUrl the value for blog_user.web_url
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.callself
     *
     * @return the value of blog_user.callself
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getCallself() {
        return callself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.callself
     *
     * @param callself the value for blog_user.callself
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setCallself(String callself) {
        this.callself = callself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.nick_name
     *
     * @return the value of blog_user.nick_name
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.nick_name
     *
     * @param nickName the value for blog_user.nick_name
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.image_name
     *
     * @return the value of blog_user.image_name
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.image_name
     *
     * @param imageName the value for blog_user.image_name
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_email
     *
     * @return the value of blog_user.user_email
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_email
     *
     * @param userEmail the value for blog_user.user_email
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.token
     *
     * @return the value of blog_user.token
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.token
     *
     * @param token the value for blog_user.token
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.salt
     *
     * @return the value of blog_user.salt
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.salt
     *
     * @param salt the value for blog_user.salt
     *
     * @mbggenerated Sun Feb 02 17:38:26 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }
}