package com.qtatelier.goverment.basics.proposal_manage.model;

import java.util.Date;

public class ProposalManger {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.id
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.title
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.corn
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String corn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.type
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.reason
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.author
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.grade
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.party
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String party;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.blog_user_id
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String blogUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.mail_no
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String mailNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.phone_num
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.job
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.e_mail
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.address
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.create_date
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.contacto
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String contacto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.company
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.telphone
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.union_anthor
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String unionAnthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.theme
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proposal_manger.content
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.id
     *
     * @return the value of proposal_manger.id
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.id
     *
     * @param id the value for proposal_manger.id
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.title
     *
     * @return the value of proposal_manger.title
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.title
     *
     * @param title the value for proposal_manger.title
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.corn
     *
     * @return the value of proposal_manger.corn
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getCorn() {
        return corn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.corn
     *
     * @param corn the value for proposal_manger.corn
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setCorn(String corn) {
        this.corn = corn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.type
     *
     * @return the value of proposal_manger.type
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.type
     *
     * @param type the value for proposal_manger.type
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.reason
     *
     * @return the value of proposal_manger.reason
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.reason
     *
     * @param reason the value for proposal_manger.reason
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.author
     *
     * @return the value of proposal_manger.author
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.author
     *
     * @param author the value for proposal_manger.author
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.grade
     *
     * @return the value of proposal_manger.grade
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.grade
     *
     * @param grade the value for proposal_manger.grade
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.party
     *
     * @return the value of proposal_manger.party
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getParty() {
        return party;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.party
     *
     * @param party the value for proposal_manger.party
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setParty(String party) {
        this.party = party;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.blog_user_id
     *
     * @return the value of proposal_manger.blog_user_id
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getBlogUserId() {
        return blogUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.blog_user_id
     *
     * @param blogUserId the value for proposal_manger.blog_user_id
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setBlogUserId(String blogUserId) {
        this.blogUserId = blogUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.mail_no
     *
     * @return the value of proposal_manger.mail_no
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getMailNo() {
        return mailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.mail_no
     *
     * @param mailNo the value for proposal_manger.mail_no
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setMailNo(String mailNo) {
        this.mailNo = mailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.phone_num
     *
     * @return the value of proposal_manger.phone_num
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.phone_num
     *
     * @param phoneNum the value for proposal_manger.phone_num
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.job
     *
     * @return the value of proposal_manger.job
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.job
     *
     * @param job the value for proposal_manger.job
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.e_mail
     *
     * @return the value of proposal_manger.e_mail
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.e_mail
     *
     * @param eMail the value for proposal_manger.e_mail
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void seteMail(String eMail) {
        this.eMail = eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.address
     *
     * @return the value of proposal_manger.address
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.address
     *
     * @param address the value for proposal_manger.address
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.create_date
     *
     * @return the value of proposal_manger.create_date
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.create_date
     *
     * @param createDate the value for proposal_manger.create_date
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.contacto
     *
     * @return the value of proposal_manger.contacto
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getContacto() {
        return contacto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.contacto
     *
     * @param contacto the value for proposal_manger.contacto
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.company
     *
     * @return the value of proposal_manger.company
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.company
     *
     * @param company the value for proposal_manger.company
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.telphone
     *
     * @return the value of proposal_manger.telphone
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.telphone
     *
     * @param telphone the value for proposal_manger.telphone
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.union_anthor
     *
     * @return the value of proposal_manger.union_anthor
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getUnionAnthor() {
        return unionAnthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.union_anthor
     *
     * @param unionAnthor the value for proposal_manger.union_anthor
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setUnionAnthor(String unionAnthor) {
        this.unionAnthor = unionAnthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.theme
     *
     * @return the value of proposal_manger.theme
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.theme
     *
     * @param theme the value for proposal_manger.theme
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proposal_manger.content
     *
     * @return the value of proposal_manger.content
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proposal_manger.content
     *
     * @param content the value for proposal_manger.content
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }
}