package com.qtatelier.goverment.basics.proposal_manage.mapper;


import com.qtatelier.goverment.basics.proposal_manage.model.ProposalManger;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ProposalMangerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proposal_manger
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proposal_manger
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    int insert(ProposalManger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proposal_manger
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    int insertSelective(ProposalManger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proposal_manger
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    ProposalManger selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proposal_manger
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    int updateByPrimaryKeySelective(ProposalManger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proposal_manger
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ProposalManger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proposal_manger
     *
     * @mbggenerated Sun Mar 01 11:44:58 CST 2020
     */
    int updateByPrimaryKey(ProposalManger record);
}